// /src/lib/onboardingEvents.ts
export const onboardingEvents = {
  // Evidence Added Events
  WEBSITE_ADDED: 'WEBSITE_ADDED',
  PDF_UPLOADED: 'PDF_UPLOADED',
  IMAGE_UPLOADED: 'IMAGE_UPLOADED',
  
  // Processing Events
  PARSING_STARTED: 'PARSING_STARTED',
  ANALYSIS_STARTED: 'ANALYSIS_STARTED',
  FUSION_STARTED: 'FUSION_STARTED',
  
  // Insight Events
  BRAND_DETECTED: 'BRAND_DETECTED',
  TONE_IDENTIFIED: 'TONE_IDENTIFIED',
  AUDIENCE_SEGMENTED: 'AUDIENCE_SEGMENTED',
  
  // Strategy Events
  STRATEGY_GENERATED: 'STRATEGY_GENERATED',
  PILLARS_IDENTIFIED: 'PILLARS_IDENTIFIED',
  RECOMMENDATIONS_READY: 'RECOMMENDATIONS_READY'
} as const;