// /src/components/home/HomeInsights.tsx
import { motion } from "framer-motion"
import { Brain, MessageSquare, Users, Hash, Star, TrendingUp } from "lucide-react"

interface HomeInsightsProps {
  insights: {
    toneSummary: string
    corePillars: string[]
    audienceSegments: string[]
    keywords: string[]
    brandArchetype: string
    writingStyle: string
  }
}

export default function HomeInsights({ insights }: HomeInsightsProps) {
  const insightCards = [
    {
      id: 'tone',
      title: 'Brand Tone',
      description: insights.toneSummary,
      icon: MessageSquare,
      color: 'from-blue-500 to-cyan-400'
    },
    {
      id: 'archetype',
      title: 'Brand Archetype',
      description: insights.brandArchetype,
      icon: Star,
      color: 'from-purple-500 to-pink-400'
    },
    {
      id: 'writing',
      title: 'Writing Style',
      description: insights.writingStyle,
      icon: Brain,
      color: 'from-emerald-500 to-teal-400'
    }
  ]

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: 0.5 }}
      className="rounded-2xl bg-gradient-to-br from-[rgb(var(--os-surface))] to-[rgb(var(--os-surface)/0.6)] border border-[rgb(var(--border))] overflow-hidden"
    >
      {/* Header */}
      <div className="p-6 border-b border-[rgb(var(--border)/0.4)]">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 rounded-lg bg-gradient-to-br from-[rgb(var(--os-accent))] to-[rgb(var(--os-accent)/0.6)] flex items-center justify-center">
            <Brain className="w-5 h-5 text-white" />
          </div>
          <div>
            <h2 className="text-xl font-semibold text-[rgb(var(--foreground))]">
              Brand Intelligence
            </h2>
            <p className="text-sm text-[rgb(var(--muted-foreground))]">
              Insights generated by Brainiark AI
            </p>
          </div>
        </div>

        {/* Key Insight Cards */}
        <div className="grid grid-cols-3 gap-4">
          {insightCards.map((card, index) => (
            <motion.div
              key={card.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.4, delay: 0.6 + index * 0.1 }}
              className="p-4 rounded-xl bg-[rgb(var(--os-surface)/0.8)] border border-[rgb(var(--border)/0.4)]"
            >
              <div className={`w-8 h-8 rounded-lg bg-gradient-to-br ${card.color} flex items-center justify-center mb-3`}>
                <card.icon className="w-4 h-4 text-white" />
              </div>
              <h3 className="font-medium text-[rgb(var(--foreground))] mb-1">
                {card.title}
              </h3>
              <p className="text-sm text-[rgb(var(--muted-foreground))]">
                {card.description}
              </p>
            </motion.div>
          ))}
        </div>
      </div>

      {/* Detailed Insights */}
      <div className="p-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Core Pillars */}
          <div className="space-y-4">
            <div className="flex items-center gap-2">
              <TrendingUp className="w-4 h-4 text-[rgb(var(--os-accent))]" />
              <h3 className="font-semibold text-[rgb(var(--foreground))]">Core Pillars</h3>
            </div>
            <div className="flex flex-wrap gap-2">
              {insights.corePillars.map((pillar, index) => (
                <motion.span
                  key={index}
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ duration: 0.3, delay: 0.8 + index * 0.1 }}
                  className="inline-flex items-center px-3 py-1.5 rounded-full bg-[rgb(var(--os-accent)/0.1)] border border-[rgb(var(--os-accent)/0.2)] text-sm font-medium text-[rgb(var(--os-accent))]"
                >
                  {pillar}
                </motion.span>
              ))}
            </div>
          </div>

          {/* Audience Segments */}
          <div className="space-y-4">
            <div className="flex items-center gap-2">
              <Users className="w-4 h-4 text-[rgb(var(--os-accent))]" />
              <h3 className="font-semibold text-[rgb(var(--foreground))]">Audience Segments</h3>
            </div>
            <div className="space-y-2">
              {insights.audienceSegments.map((segment, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ duration: 0.3, delay: 0.9 + index * 0.1 }}
                  className="flex items-center gap-2"
                >
                  <div className="w-2 h-2 rounded-full bg-[rgb(var(--os-accent))]" />
                  <span className="text-sm text-[rgb(var(--foreground))]">{segment}</span>
                </motion.div>
              ))}
            </div>
          </div>

          {/* Keywords */}
          <div className="md:col-span-2 space-y-4">
            <div className="flex items-center gap-2">
              <Hash className="w-4 h-4 text-[rgb(var(--os-accent))]" />
              <h3 className="font-semibold text-[rgb(var(--foreground))]">Key Brand Keywords</h3>
            </div>
            <div className="flex flex-wrap gap-2">
              {insights.keywords.map((keyword, index) => (
                <motion.span
                  key={index}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.3, delay: 1 + index * 0.05 }}
                  className="inline-flex items-center px-3 py-1.5 rounded-lg bg-[rgb(var(--os-surface)/0.8)] border border-[rgb(var(--border)/0.4)] text-sm font-medium text-[rgb(var(--foreground))] hover:border-[rgb(var(--os-accent)/0.3)] transition-colors"
                >
                  #{keyword}
                </motion.span>
              ))}
            </div>
          </div>
        </div>

        {/* AI Status */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 1.5 }}
          className="mt-6 pt-6 border-t border-[rgb(var(--border)/0.4)]"
        >
          <div className="flex items-center gap-3">
            <div className="relative">
              <div className="w-3 h-3 rounded-full bg-emerald-500 animate-ping" />
              <div className="absolute inset-0 w-3 h-3 rounded-full bg-emerald-500" />
            </div>
            <p className="text-sm text-[rgb(var(--muted-foreground))]">
              <span className="font-medium text-[rgb(var(--foreground))]">Brainiark AI</span> is actively analyzing your brand data to provide deeper insights
            </p>
          </div>
        </motion.div>
      </div>
    </motion.div>
  )
}